plugins {
    id("org.jetbrains.intellij") version "1.17.4"
    id("org.jetbrains.kotlin.jvm") version "1.9.25"
}

group = "com.codotchi"
version = "2.27.3"

repositories {
    mavenCentral()
}

// Separate configuration so the standalone launcher fat-jar can be resolved
// independently and placed first on the JavaExec classpath.
val junitConsole: Configuration by configurations.creating

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    junitConsole("org.junit.platform:junit-platform-console-standalone:1.10.2")
}

intellij {
    version.set("2024.1")
    type.set("IC")   // IntelliJ Community
    plugins.set(listOf())
    updateSinceUntilBuild.set(false)
}

kotlin {
    jvmToolchain(21)
}

// Leaderboard HMAC key (see Integrity.kt). Never committed: read from the
// CODOTCHI_LEADERBOARD_KEY env var or the repo-root .leaderboard-key file and
// baked into a gitignored generated source file. Empty when neither exists —
// the plugin still builds and plays, it just can't submit to the leaderboard.
// Only locals are captured by doLast so the task stays configuration-cache safe.
val generateLeaderboardKey by tasks.registering {
    description = "Generates generated/LeaderboardKey.kt from CODOTCHI_LEADERBOARD_KEY or .leaderboard-key."
    val leaderboardKeyFile = rootProject.file("../.leaderboard-key")
    val generatedLeaderboardKey = file("src/main/kotlin/com/codotchi/generated/LeaderboardKey.kt")
    val envKey = providers.environmentVariable("CODOTCHI_LEADERBOARD_KEY").orElse("")
    inputs.property("envKey", envKey)
    inputs.files(leaderboardKeyFile).optional()
    outputs.file(generatedLeaderboardKey)
    doLast {
        val key = envKey.get().trim().ifEmpty {
            if (leaderboardKeyFile.isFile) leaderboardKeyFile.readText(Charsets.UTF_8).trim() else ""
        }
        val escaped = buildString {
            for (c in key) {
                when (c) {
                    '\\' -> append("\\\\")
                    '"'  -> append("\\\"")
                    '$'  -> append("\\$")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> if (c.code < 0x20 || c.code > 0x7e) append("\\u%04x".format(c.code)) else append(c)
                }
            }
        }
        generatedLeaderboardKey.parentFile.mkdirs()
        generatedLeaderboardKey.writeText(
            "// GENERATED by build.gradle.kts (generateLeaderboardKey) — do not edit, never commit.\n" +
            "package com.codotchi.generated\n\n" +
            "object LeaderboardKey {\n" +
            "    const val VALUE: String = \"$escaped\"\n" +
            "}\n",
            Charsets.UTF_8
        )
    }
}

tasks {
    compileKotlin {
        dependsOn(generateLeaderboardKey)
    }

    buildSearchableOptions {
        enabled = false
    }

    // The webview (sidebar + sprite preview) is shared with the VS Code
    // extension. vscode/media is the source of truth: copy it into the plugin's
    // webview/ resources at build time instead of keeping a hand-made copy.
    processResources {
        from("../vscode/media") {
            include(
                "sidebar.js", "sidebar.css", "sidebar.html",
                "customCharacters.js", "spriteConstants.js", "sprites.generated.js", "sprites.js", "minigameArt.js",
                "backgroundArt.js", "sprite_preview.html"
            )
            into("webview")
        }
    }

    // The org.jetbrains.intellij plugin hooks into ALL tasks of type `Test`
    // during the configuration phase (not just the one named "test") and
    // tries to extract the JBR runtime.  On Windows this fails with a
    // file-lock error on extnet.dll whenever any IDE or Java process already
    // has the JBR open.
    //
    // Solution: run tests via JavaExec (not Test) so the plugin never touches
    // the task.  The JUnit Platform Console Standalone launcher is used to
    // discover and execute JUnit 5 tests from the compiled test classes dir.
    //
    // Usage: gradlew unitTest --no-configuration-cache
    //        (from pycharm/)
    //
    // Do NOT run `gradlew test` — that is the IntelliJ-sandbox path.

    val copySourceForTest by registering(Copy::class) {
        description = "Copies CodotchiPlugin.kt into test resources for source-guard tests."
        from("src/main/kotlin/com/codotchi/CodotchiPlugin.kt")
        into(layout.buildDirectory.dir("resources/test/source"))
    }

    val unitTest by registering(JavaExec::class) {
        description = "Runs pure JUnit 5 unit tests via JavaExec (bypasses IntelliJ plugin hooks)."
        group       = "verification"

        dependsOn("compileTestKotlin", "processResources", copySourceForTest)

        // Resolve the fat-jar and test classpath at configuration time.
        val launcherJar = junitConsole.resolvedConfiguration.resolvedArtifacts
            .first { it.name == "junit-platform-console-standalone" }
            .file
        // Use the Kotlin-specific output dir directly — classesDirs.asPath returns
        // a semicolon-separated list (kotlin + java dirs) which --scan-class-path
        // treats as a single non-existent path on Windows, finding 0 tests.
        val testClassesDir   = layout.buildDirectory.dir("classes/kotlin/test").get().asFile.absolutePath
        val mainClassesDir   = layout.buildDirectory.dir("classes/kotlin/main").get().asFile.absolutePath
        val testRuntimeCp    = configurations["testRuntimeClasspath"].asPath
        // Main resources (webview/*.js, webview/sidebar.html, META-INF/) must be
        // on the test classpath so BrowserPanelHtmlTest can load them.
        val mainResourcesDir = sourceSets["main"].output.resourcesDir!!.absolutePath
        val extraResources   = layout.buildDirectory.dir("resources/test").get().asFile.absolutePath

        // File.pathSeparator (";" on Windows, ":" elsewhere) so CI on Linux works too.
        val fullCp = listOf(testClassesDir, mainClassesDir, testRuntimeCp, mainResourcesDir, extraResources)
            .joinToString(File.pathSeparator)

        classpath(launcherJar)
        mainClass.set("org.junit.platform.console.ConsoleLauncher")
        args(
            "--scan-class-path", testClassesDir,
            "--class-path", fullCp,
            "--details", "tree",
            "--fail-if-no-tests"
        )
    }
}



